name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t vohoangkh4ng/fastapi-hello-world:latest .

    - name: Push Docker Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push vohoangkh4ng/fastapi-hello-world:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.28.0

    - name: Configure kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: echo "$KUBECONFIG" > kubeconfig

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
